version: "3.9"
services:
  api:
    image: example-docker-diy:latest
    build:
        context: ..
        dockerfile: ./example-docker-diy/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
